CREATE TABLE IF NOT EXISTS moisture (
    time TIMESTAMP NOT NULL, 
    upi_id INTEGER NOT NULL,
    value DECIMAL(5, 2) NOT NULL
);


CREATE TABLE IF NOT EXISTS temperature (
    time TIMESTAMP NOT NULL, 
    upi_id INTEGER NOT NULL,
    value DECIMAL(5, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS upis (
    id SERIAL PRIMARY KEY,
    upi_name TEXT
);