version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5437:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - grafana_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - postgres
    networks:
      - grafana_network

  python_app:
    build: ./python_app
    container_name: python_app
    depends_on:
      - postgres
    networks:
      - grafana_network

  processor:
    build: ./processor
    container_name: processor
    depends_on:
      - postgres
    networks:
      - grafana_network

volumes:
  pgdata:
  grafana_data:

networks:
  grafana_network:
