{
 "title": "UPI 1 - Unidade de Produção Independente",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "upi", "label": "UPI", "query": "1, 2" }
  ]
 },
 "panels": [
  {
   "type": "canvas",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time AS \"time\",\r\n  value\r\nFROM\r\n  temperature\r\nWHERE\r\n  $__timeFilter(time)\r\nORDER BY\r\n  time ASC\r\n"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH RankedTemperatures AS (\r\n  SELECT\r\n    time,\r\n    upi_id,\r\n    value,\r\n    ROW_NUMBER() OVER (\r\n      ORDER BY\r\n        time DESC\r\n    ) AS rn\r\n  FROM\r\n    temperature\r\n  WHERE\r\n    $__timeFilter(time)\r\n  AND \r\n    upi_id = $upi \r\n),\r\nLastValues AS (\r\n  SELECT\r\n    MAX(\r\n      CASE\r\n        WHEN rn = 1 THEN value\r\n      END\r\n    ) AS last_value,\r\n    MAX(\r\n      CASE\r\n        WHEN rn = 2 THEN value\r\n      END\r\n    ) AS second_last_value\r\n  FROM\r\n    RankedTemperatures\r\n)\r\nSELECT\r\n  last_value,\r\n  second_last_value,\r\n  CASE\r\n    WHEN second_last_value IS NULL\r\n    OR second_last_value = 0 THEN NULL\r\n    ELSE (\r\n      (last_value - second_last_value) / second_last_value\r\n    ) * 100\r\n  END AS percentage_variation\r\nFROM\r\n  LastValues;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "\r\n<div style=\"width: 100%; height: 100%; background: #23282F; display: flex; align-items: center; justify-content: center; flex-direction: column\">\r\n  <img height=\"300px\" src=\"https://raw.githubusercontent.com/wrlxavier/imgs-dash/main/estufa.png\">\r\n  <h2>Unidade de Produção Independente ${upi}</h2>\r\n</div>"
   }
  },
  {
   "title": "Temperatura ao longo do tempo",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time AS \"time\",\r\n  upi_id,\r\n  value\r\nFROM\r\n  temperature\r\nWHERE\r\n  $__timeFilter(time)\r\nAND\r\n  upi_id = $upi \r\nORDER BY\r\n  time ASC\r\n"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time AS \"time\",\r\n  value\r\nFROM\r\n  moisture\r\nWHERE\r\n  $__timeFilter(time)\r\nORDER BY\r\n  time ASC\r\n"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH RankedMoistures AS (\r\n  SELECT\r\n    time,\r\n    upi_id,\r\n    value,\r\n    ROW_NUMBER() OVER (ORDER BY time DESC) AS rn\r\n  FROM\r\n    moisture\r\n  WHERE\r\n    $__timeFilter(time)\r\n  AND \r\n    upi_id = $upi \r\n)\r\n, LastValues AS (\r\n  SELECT\r\n    MAX(CASE WHEN rn = 1 THEN value END) AS last_value,\r\n    MAX(CASE WHEN rn = 2 THEN value END) AS second_last_value\r\n  FROM\r\n    RankedMoistures\r\n)\r\nSELECT\r\n  last_value,\r\n  second_last_value,\r\n  CASE\r\n    WHEN second_last_value IS NULL OR second_last_value = 0 THEN NULL\r\n    ELSE ((last_value - second_last_value) / second_last_value) * 100\r\n  END AS percentage_variation\r\nFROM\r\n  LastValues;\r\n"
    }
   ]
  },
  {
   "title": "Qualidade Temperatua",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time AS \"time\",\r\n  value\r\nFROM\r\n  temperature\r\nWHERE\r\n  $__timeFilter(time)\r\nORDER BY\r\n  time ASC\r\n"
    }
   ]
  },
  {
   "title": "Qualidade Umidade Relativa",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  --time AS \"time\",\r\n  value\r\nFROM\r\n  moisture\r\nWHERE\r\n  $__timeFilter(time)\r\nORDER BY\r\n  time ASC\r\n"
    }
   ]
  },
  {
   "title": "Umidade ao longo do tempo",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time AS \"time\",\r\n  upi_id,\r\n  value\r\nFROM\r\n  moisture\r\nWHERE\r\n  $__timeFilter(time)\r\nAND\r\n  upi_id = $upi \r\nORDER BY\r\n  time ASC\r\n"
    }
   ]
  },
  {
   "title": "Alarmes acionados",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time AS \"time\",\r\n  value\r\nFROM\r\n  temperature\r\nWHERE\r\n  $__timeFilter(time)\r\nORDER BY\r\n  time ASC\r\nlimit 2"
    }
   ]
  }
 ]
}